cmake_minimum_required(VERSION 3.10)
project(CENG4120_Computer-Aided_Design_of_Very_Large_Scale_Integrated_Circuits)

# Add an executable
add_executable(CENG4120_Computer-Aided_Design_of_Very_Large_Scale_Integrated_Circuits hw2.cpp)

# Optionally, specify include directories if needed
# include_directories(include)

# Optionally, specify libraries if needed
# link_libraries(library)